### ISSUE TITLE
browser.getMetrics is not a function

### ISSUE THREAD

**Issue by freedombycrypto** [christian-bromann/webdriverio-performance-testing#9] opened 2022-04-30 00:10 UTC
I have cloned this project and got couple of errors while running test [webdriverio-performance-testing](https://github.com/christian-bromann/webdriverio-performance-testing)

Error 1:  Below error shows because of fiber. it does not support node 16.x or above. So work around, i've deleted fiber from node modules. (`my node version: v16.14.2`)

```
Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file coroutine.cc, line 134. zsh: abort npm run test:local
```

Error 2: I've updated latest packages in package.json and while running test, i got `browser.getMetrics is not a function`.

npm package
```
"@babel/cli": "^7.17.10",
"@babel/core": "^7.17.10",
"@babel/preset-env": "^7.17.10",
"@babel/register": "^7.17.7",
"@wdio/cli": "^7.19.6",
"@wdio/devtools-service": "^7.19.6",
"@wdio/local-runner": "^7.19.5",
"@wdio/mocha-framework": "^7.19.5",
"@wdio/spec-reporter": "^7.19.5",
"@wdio/sync": "^7.19.5",
"chai": "^4.3.6",
"chromedriver": "^100.0.0",
"wdio-chromedriver-service": "^7.3.2",
"webdriverio": "^7.19.5"
```
wdio-chromedriver.log

```
Starting ChromeDriver 100.0.4896.60 (6a5d10861ce8de5fce22564658033b43cb7de047-refs/branch-heads/4896@{#875}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

```

wdio-log
```
2022-04-30T00:19:33.131Z DEBUG @wdio/utils:initialiseServices: initialise service "devtools" as NPM package
2022-04-30T00:19:34.245Z DEBUG @wdio/utils:initialiseServices: initialise service "chromedriver" as NPM package
2022-04-30T00:19:34.305Z INFO @wdio/cli:launcher: Run onPrepare hook
2022-04-30T00:19:34.307Z INFO chromedriver: Start Chromedriver (/Users/user/webdriverio-performance-testing/node_modules/chromedriver/lib/chromedriver/chromedriver) with args --port=9515 --url-base=/
2022-04-30T00:19:34.427Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 122ms
2022-04-30T00:19:34.429Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2022-04-30T00:19:34.429Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2022-04-30T00:19:34.430Z INFO @wdio/local-runner: Start worker 0-0 with arg: wdio.local.conf.js
2022-04-30T00:19:44.139Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
2022-04-30T00:19:44.139Z INFO @wdio/cli:launcher: Run onWorkerEnd hook
2022-04-30T00:19:44.140Z DEBUG @wdio/cli:utils: Finished to run "onWorkerEnd" hook in 0ms
2022-04-30T00:19:44.140Z INFO @wdio/cli:launcher: Run onComplete hook
2022-04-30T00:19:44.140Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms
2022-04-30T00:19:44.166Z INFO @wdio/local-runner: Shutting down spawned worker
2022-04-30T00:19:44.417Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully

```

there are no errors in the log but when i run the test, i got an error

```
[chrome 100.0.4896.127 mac os x #0-0] 1) My Performance Test "before all" hook for My Performance Test
[chrome 100.0.4896.127 mac os x #0-0] browser.getMetrics is not a function
[chrome 100.0.4896.127 mac os x #0-0] TypeError: browser.getMetrics is not a function
[chrome 100.0.4896.127 mac os x #0-0]     at Context.<anonymous> (/Users/user/webdriverio-performance-testing/tests/performance.test.js:9:27)
```

**Comment by christian-bromann** [comment] 2022-05-01 15:09
duplicate of #7

**Closed as completed by christian-bromann** 2022-05-01 15:09 UTC
